version: '3.8'
services:
  chromium:
    image: lscr.io/linuxserver/chromium:latest
    container_name: WingsNodeTeam
    privileged: true
    environment:
      - TITLE=WingsNodeTeam
      - DISPLAY=:1
      - PUID=1000
      - PGID=1000
      - CUSTOM_USER=${USERNAME}
      - PASSWORD=${PASSWORD}
      - LANGUAGE=en_US.UTF-8
      - CHROME_CLI=https://app.getgrass.io/register/?referralCode=Auv6lEKD7aBCRAM https://app.gradient.network/signup?code=30U08D https://app.blockmesh.xyz/register?invite_code=1140b118-e63d-415f-b02b-a327b933debe https://app.nodepay.ai/register?ref=JpxFKavaDveyFUL
    volumes:
      - ${HOME}/chromium/config:/config
    ports:
      - "0.0.0.0:${PORT}:3000"  
    shm_size: '4gb'
    restart: unless-stopped
